#!/usr/bin/env python

from sys import platform
import subprocess

try:
	import click
	from core.utiliset.secretgenerate import create_or_load_secret_key

	@click.command()
	def secretgenerate():
		generate = create_or_load_secret_key()

	@click.command()
	def run():
		
		"""
		Команда для запуска 
		"""

		if platform.startswith('win'):
			subprocess.run("cls", shell=True)
		elif platform.startswith("linux"):
			subprocess.run("clear", shell=True)

		subprocess.run([
			"py",
			".\main.py"
		])

	@click.group()
	def cli():
		pass

	cli.add_command(run)
	cli.add_command(secretgenerate)

except ModuleNotFoundError:
	print("Требуется виртуальное окружение")


if __name__ == "__main__":
    if platform.startswith("win"):
        cli()
    else:
        cli()