#!/usr/bin/env python

from sys import platform
import subprocess
from core.utiliset.init_env import get_venv

def checkOperatingSystem():
	if platform.startswith('win'):
		subprocess.run("cls", shell=True)
		return "win"
	elif platform.startswith("linux"):
		subprocess.run("clear", shell=True)
		return "all"

try:
	import click
	from core.utiliset.secretgenerate import create_or_load_secret_key

	@click.command()
	def secretgenerate():
		generate = create_or_load_secret_key()

	@click.command()
	def run():
		
		"""
		Команда для запуска сервера
		"""

		if checkOperatingSystem() == "win":
			subprocess.run("py main.py", shell=True)
		else:
			subprocess.run("python3 main.py", shell=True)

	@click.group()
	def cli():
		pass

	cli.add_command(run)
	cli.add_command(secretgenerate)

except ModuleNotFoundError:
	cli = None


if __name__ == "__main__":
	if get_venv():
		if cli:
			cli()